import { StyleSheet } from 'react-native';
import Colors from '@/constants/Colors';
import { SPACING, FONT_SIZES, BORDER_RADIUS } from '@/constants/Theme';

export default (theme: 'light' | 'dark') =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor:
        theme === 'dark' ? Colors.dark.background : Colors.light.background,
    },
    card: {
      backgroundColor: theme === 'dark' ? '#1A1A1A' : '#FFF',
      padding: SPACING.lg,
      marginVertical: SPACING.sm,
      borderRadius: BORDER_RADIUS.xl,
      borderWidth: 1,
      borderColor: theme === 'dark' ? '#333333' : '#E5E7EB',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
      elevation: 5,
    },
    header: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: SPACING.md,
      paddingHorizontal: SPACING.md,
      paddingVertical: SPACING.sm,
    },
    title: {
      fontSize: FONT_SIZES.lg,
      fontWeight: '600',
      color: theme === 'dark' ? Colors.dark.text : Colors.light.text,
      flex: 1,
      marginRight: SPACING.sm,
    },
    statusText: {
      fontSize: FONT_SIZES.sm,
      fontWeight: '600',
      paddingHorizontal: SPACING.md,
      paddingVertical: SPACING.xs,
      borderRadius: BORDER_RADIUS.md,
      backgroundColor: Colors.dark.tint,
      color: '#FFFFFF',
    },
    content: {
      fontSize: FONT_SIZES.md,
      color: '#B0B0B0',
      marginBottom: SPACING.md,
      lineHeight: 22,
    },
    authorSection: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: SPACING.md,
      paddingTop: SPACING.md,
      borderTopWidth: 1,
      borderTopColor: '#333333',
    },
    author: {
      fontSize: FONT_SIZES.sm,
      color: Colors.dark.tint,
      fontWeight: '600',
    },
    date: {
      fontSize: FONT_SIZES.sm,
      color: '#888888',
    },
    statsContainer: {
      flexDirection: 'row',
      justifyContent: 'space-around',
      paddingVertical: SPACING.md,
      borderTopWidth: 1,
      borderBottomWidth: 1,
      borderColor: '#333333',
      backgroundColor: '#0F0F0F',
    },
    statItem: {
      alignItems: 'center',
    },
    statLabel: {
      fontSize: FONT_SIZES.xs,
      color: '#888888',
      marginBottom: 4,
    },
    statValue: {
      fontSize: FONT_SIZES.md,
      color: Colors.dark.text,
      fontWeight: '600',
    },
    tagsContainer: {
      marginTop: SPACING.md,
    },
    tags: {
      fontSize: FONT_SIZES.sm,
      color: Colors.dark.tint,
      fontStyle: 'italic',
    },
    // Detalle
    detailContainer: {
      flex: 1,
      padding: SPACING.lg,
      backgroundColor:
        theme === 'dark' ? Colors.dark.background : Colors.light.background,
    },
    detailCard: {
      backgroundColor: theme === 'dark' ? '#1A1A1A' : '#FFF',
      borderRadius: BORDER_RADIUS.lg,
      padding: SPACING.lg,
      borderWidth: 1,
      borderColor: theme === 'dark' ? '#333333' : '#E5E7EB',
    },
    detailText: {
      color: theme === 'dark' ? Colors.dark.text : Colors.light.text,
      fontSize: FONT_SIZES.sm,
    },
    error: {
      color: Colors.dark.tint,
      marginTop: SPACING.md,
    },
    formContainer: {
      flex: 1,
      backgroundColor: Colors.dark.background,
      padding: SPACING.lg,
    },
    formTitle: {
      fontSize: FONT_SIZES.xl,
      fontWeight: '600',
      color: Colors.dark.text,
      marginBottom: SPACING.lg,
    },
    formLabel: {
      fontSize: FONT_SIZES.md,
      fontWeight: '500',
      color: Colors.dark.text,
      marginBottom: SPACING.xs,
    },
    textarea: {
      width: '100%',
      minHeight: 120,
      borderWidth: 1,
      borderColor: '#333333',
      borderRadius: BORDER_RADIUS.md,
      padding: SPACING.md,
      color: Colors.dark.text,
      backgroundColor: theme === 'dark' ? '#0F0F0F' : '#FFFFFF',
      marginBottom: SPACING.md,
    },
    formRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      gap: SPACING.md,
      marginBottom: SPACING.md,
    },
    info: {
      color: theme === 'dark' ? Colors.dark.text : Colors.light.text,
      marginTop: SPACING.md,
    },
    // Estados de carga, error y vacío
    loadingContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      paddingVertical: SPACING.xl,
    },
    loadingText: {
      fontSize: FONT_SIZES.md,
      color: theme === 'dark' ? Colors.dark.text : Colors.light.text,
    },
    errorContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      paddingVertical: SPACING.xl,
    },
    errorText: {
      color: Colors.dark.tint,
      fontSize: FONT_SIZES.md,
      marginBottom: SPACING.md,
      textAlign: 'center',
    },
    retryText: {
      color: Colors.dark.tint,
      fontWeight: 'bold',
      fontSize: FONT_SIZES.md,
      textAlign: 'center',
      textDecorationLine: 'underline',
      marginTop: SPACING.sm,
    },
    emptyContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      paddingVertical: SPACING.xl,
    },
    emptyTitle: {
      fontSize: FONT_SIZES.lg,
      fontWeight: '600',
      color: theme === 'dark' ? Colors.dark.text : Colors.light.text,
      marginBottom: SPACING.md,
    },
    emptyMessage: {
      fontSize: FONT_SIZES.md,
      color: '#888888',
      textAlign: 'center',
    },
    feedHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: SPACING.md,
      paddingVertical: SPACING.sm,
      backgroundColor:
        theme === 'dark' ? Colors.dark.background : Colors.light.background,
      borderBottomWidth: 1,
      borderBottomColor: theme === 'dark' ? '#333' : '#f0f0f0',
    },
    actionsContainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginTop: SPACING.md,
      paddingTop: SPACING.sm,
      borderTopWidth: 1,
      borderTopColor: theme === 'dark' ? '#333' : '#f0f0f0',
      gap: SPACING.sm,
    },
    headerTitle: {
      fontSize: FONT_SIZES.xl,
      fontWeight: '700',
      color: theme === 'dark' ? Colors.dark.text : Colors.light.text,
      flex: 1,
    },
    list: {
      flex: 1,
    },
    listContent: {
      paddingVertical: SPACING.md,
      paddingHorizontal: SPACING.sm,
    },
    retryButton: {
      color: Colors.dark.tint,
      fontSize: FONT_SIZES.md,
      fontWeight: '600',
      textAlign: 'center',
      marginTop: SPACING.md,
      textDecorationLine: 'underline',
    },
    emptyText: {
      fontSize: FONT_SIZES.md,
      color: theme === 'dark' ? Colors.dark.text : Colors.light.text,
      textAlign: 'center',
      marginBottom: SPACING.lg,
    },
    // Nuevo estado vacío mejorado
    emptyStateContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      paddingVertical: SPACING.xl * 2,
      paddingHorizontal: SPACING.lg,
    },
    emptyIcon: {
      width: 100,
      height: 100,
      borderRadius: 50,
      backgroundColor: Colors.dark.tint,
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: SPACING.xl,
      shadowColor: Colors.dark.tint,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
      elevation: 8,
    },
    emptyIconText: {
      fontSize: 40,
    },
    emptySubtext: {
      fontSize: FONT_SIZES.sm,
      color: '#888888',
      textAlign: 'center',
      marginTop: SPACING.md,
      lineHeight: 20,
    },
    emptyActions: {
      marginTop: SPACING.xl * 1.5,
      alignItems: 'center',
      gap: SPACING.md,
    },
    uploadButton: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: Colors.dark.tint,
      paddingHorizontal: SPACING.xl,
      paddingVertical: SPACING.md,
      borderRadius: BORDER_RADIUS.xl,
      shadowColor: Colors.dark.tint,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
      elevation: 8,
      gap: SPACING.sm,
    },
    uploadButtonIcon: {
      fontSize: 20,
    },
    uploadButtonText: {
      color: '#FFFFFF',
      fontSize: FONT_SIZES.md,
      fontWeight: '600',
    },
    refreshButton: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: 'transparent',
      paddingHorizontal: SPACING.lg,
      paddingVertical: SPACING.sm,
      borderRadius: BORDER_RADIUS.lg,
      borderWidth: 2,
      borderColor: theme === 'dark' ? '#333333' : '#E5E7EB',
      gap: SPACING.sm,
    },
    refreshButtonIcon: {
      fontSize: 16,
    },
    refreshButtonText: {
      color: theme === 'dark' ? Colors.dark.text : Colors.light.text,
      fontSize: FONT_SIZES.sm,
      fontWeight: '500',
    },
    listContainer: {
      paddingBottom: SPACING.xl,
    },
    separator: {
      height: SPACING.sm,
    },
    // Infinite scroll footer
    footerContainer: {
      padding: SPACING.xl,
      alignItems: 'center',
      justifyContent: 'center',
    },
    footerText: {
      fontSize: FONT_SIZES.sm,
      color: '#888888',
      textAlign: 'center',
      fontStyle: 'italic',
    },
  });
