export interface User {
  Id: string;
  Email: string;
  Password: string;
  IdEps: string | null;
  Name: string | null;
  LastName: string | null;
  UserName: string | null;
  IdGender: string | null;
  BirthDate: string | null;
  ProfileImageUrl: string | null;
  DocumentTypeId: string | null;
  Phone: string | null;
  CountryId: string | null;
  Address: string | null;
  CityId: string | null;
  RegionId: string | null;
  Rh: string | null;
  EmergencyName: string | null;
  EmergencyPhone: string | null;
  PhysicalExceptions: string | null;
  PhysicalExceptionsNotes: string | null;
  CreatedAt: string;
  UpdatedAt: string | null;
  DeletedAt: string | null;
  Ip: string | null;
  IsActive: boolean;
  UserTypeId: string | null;
  PlanId: string | null;
  UserFitUserUserId: string | null;
  UserDietUserId: string | null;
  GymUserId: string | null;
  EmployeeRegisterDailyUserUserId: string | null;
  ScheduleUserUserId: string | null;
  UserEmployeeUserUserId: string | null;
  GymId: string | null;
  RegistrationCompleted: boolean;
  BillUserSellers: unknown[];
  BillUsers: unknown[];
  Dailies: unknown[];
  DailyHistories: unknown[];
  Diets: unknown[];
  EmployeeRegisterDailyUserUser: unknown;
  Gym: unknown;
  LogChanges: unknown[];
  LogErrors: unknown[];
  LogLogins: unknown[];
  LogUninstalls: unknown[];
  NotificationOptions: unknown[];
  Notifications: unknown[];
  Permissions: unknown[];
  PhysicalAssessments: unknown[];
  Plan: unknown;
  RoutineAssigneds: unknown[];
  RoutineTemplates: unknown[];
  ScheduleUserUser: unknown;
  UserDietUser: unknown;
  UserEmployeeUser: unknown;
  UserFitUser: unknown;
  GymUser: unknown;
  UserType: unknown;
  PaymentAttempts: unknown[];
  Posts: unknown[];
  Comments: unknown[];
  Likes: unknown[];
}
