export interface User {
  Id: string;
  Email: string;
  Password: string;
  IdEps: string | null;
  Name: string | null;
  LastName: string | null;
  UserName: string | null;
  IdGender: string | null;
  BirthDate: string | null;
  ProfileImageUrl: string | null;
  DocumentTypeId: string | null;
  Phone: string | null;
  CountryId: string | null;
  Address: string | null;
  CityId: string | null;
  RegionId: string | null;
  Rh: string | null;
  EmergencyName: string | null;
  EmergencyPhone: string | null;
  PhysicalExceptions: string | null;
  PhysicalExceptionsNotes: string | null;
  CreatedAt: string;
  UpdatedAt: string | null;
  DeletedAt: string | null;
  Ip: string | null;
  IsActive: boolean;
  UserTypeId: string | null;
  PlanId: string | null;
  UserFitUserUserId: string | null;
  UserDietUserId: string | null;
  GymUserId: string | null;
  EmployeeRegisterDailyUserUserId: string | null;
  ScheduleUserUserId: string | null;
  UserEmployeeUserUserId: string | null;
  GymId: string | null;
  RegistrationCompleted: boolean;
  BillUserSellers: any[];
  BillUsers: any[];
  Dailies: any[];
  DailyHistories: any[];
  Diets: any[];
  EmployeeRegisterDailyUserUser: any;
  Gym: any;
  LogChanges: any[];
  LogErrors: any[];
  LogLogins: any[];
  LogUninstalls: any[];
  NotificationOptions: any[];
  Notifications: any[];
  Permissions: any[];
  PhysicalAssessments: any[];
  Plan: any;
  RoutineAssigneds: any[];
  RoutineTemplates: any[];
  ScheduleUserUser: any;
  UserDietUser: any;
  UserEmployeeUser: any;
  UserFitUser: any;
  GymUser: any;
  UserType: any;
  PaymentAttempts: any[];
  Posts: any[];
  Comments: any[];
  Likes: any[];
}
