export interface FindGymsByNameResponse {
  Id: string;
  Name: string;
  Nit: string;
  Email: string;
  LogoUrl: string | null;
  Description: string;
  PhoneNumber: string | null;
  WebsiteUrl: string | null;
  SocialMediaLinks: string | null;
  LegalRepresentative: string | null;
  BillingEmail: string | null;
  SubscriptionPlanId: string | null;
  IsVerified: boolean;
  Tags: string | null;
  Owner_UserId: string;
  BrandColor: string | null;
  MaxBranchesAllowed: number | null;
  QrImageUrl: string | null;
  TrialEndsAt: string | null;
  CountryId: string;
  CreatedAt: string;
  UpdatedAt: string;
  DeletedAt: string | null;
  Ip: string | null;
  IsActive: boolean;
  GymTypeId: string;
  GymType: any;
  Bills: any[];
  Branches: any[];
  GymPlanSelecteds: any[];
  Plans: any[];
  RoutineTemplates: any[];
  UserGyms: any[];
  PaymentAttempts: any[];
  FacbookUrl: string | null;
  InstagramUrl: string | null;
  Slogan: string | null;
  PaisId: string | null;
}
