import { StyleSheet } from 'react-native';
import Colors from '@/constants/Colors';
import type { ThemeMode } from '@/hooks/useThemedStyles';

export const makeGymPlanViewStyles = (theme: ThemeMode) => {
  const isDark = theme === 'dark';
  const palette = Colors[theme];
  const colors = {
    background: palette.background,
    cardBg: isDark ? '#1a1a1a' : '#F7F7F7',
    surface2: isDark ? '#111111' : '#FFFFFF',
    border: isDark ? '#333333' : '#DDDDDD',
    text: palette.text,
    muted: isDark ? '#CCCCCC' : '#666666',
    dim: isDark ? '#888888' : '#999999',
    tint: palette.tint,
    success: '#50E3C2',
    info: '#2196F3',
    warning: '#FFB86C',
    danger: '#FF6B6B',
    onTint: '#FFFFFF',
  } as const;

  const styles = StyleSheet.create({
    container: { flex: 1, backgroundColor: colors.background },
    loadingContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: colors.background,
    },
    loadingText: { color: colors.text, marginTop: 16, fontSize: 16 },
    errorContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: colors.background,
      padding: 20,
    },
    errorText: {
      color: colors.danger,
      textAlign: 'center',
      marginVertical: 16,
      fontSize: 16,
    },
    retryButton: {
      backgroundColor: colors.tint,
      paddingHorizontal: 20,
      paddingVertical: 10,
      borderRadius: 8,
    },
    retryButtonText: { color: colors.onTint, fontWeight: 'bold' },
    compactWrapper: { paddingHorizontal: 20, paddingTop: 12 },
    compactCard: {
      backgroundColor: colors.cardBg,
      borderRadius: 10,
      padding: 14,
      borderWidth: 1,
      borderColor: colors.border,
    },
    compactSummaryRow: { flexDirection: 'row', alignItems: 'center' },
    compactTitle: {
      color: colors.text,
      fontSize: 18,
      fontWeight: '600',
      marginBottom: 2,
    },
    compactSubtitle: { color: colors.muted, fontSize: 12 },
    compactDetails: { marginTop: 10 },
    sectionTitle: {
      fontSize: 24,
      fontWeight: 'bold',
      color: colors.text,
      marginBottom: 16,
    },
    availablePlansContainer: { padding: 20 },
    planCard: {
      backgroundColor: colors.cardBg,
      borderRadius: 12,
      padding: 20,
      marginBottom: 16,
      borderWidth: 1,
      borderColor: colors.border,
    },
    planHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 12,
    },
    planInfo: { flex: 1 },
    planName: {
      fontSize: 20,
      fontWeight: 'bold',
      color: colors.text,
      marginBottom: 4,
    },
    currentPlanName: {
      fontSize: 24,
      fontWeight: 'bold',
      color: colors.text,
      marginBottom: 4,
    },
    planPrice: { fontSize: 18, fontWeight: '600', color: colors.tint },
    planDescription: {
      color: colors.muted,
      fontSize: 14,
      marginBottom: 16,
      lineHeight: 20,
    },
    activeBadge: {
      backgroundColor: colors.success,
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 16,
    },
    availableBadge: {
      backgroundColor: colors.tint,
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 16,
    },
    activeText: { color: '#000000', fontSize: 12, fontWeight: 'bold' },
    availableText: { color: colors.onTint, fontSize: 12, fontWeight: 'bold' },
    planDetails: { marginTop: 16 },
    detailRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 12 },
    detailLabel: {
      color: colors.muted,
      fontSize: 14,
      marginLeft: 12,
      marginRight: 8,
      minWidth: 100,
    },
    detailValue: {
      color: colors.text,
      fontSize: 14,
      fontWeight: '500',
      flex: 1,
    },
    selectButton: {
      backgroundColor: colors.tint,
      paddingVertical: 12,
      paddingHorizontal: 24,
      borderRadius: 8,
      alignItems: 'center',
      justifyContent: 'center',
      minHeight: 44,
    },
    selectButtonDisabled: {
      backgroundColor: isDark ? '#666666' : '#BBBBBB',
      opacity: 0.6,
    },
    selectButtonText: {
      color: colors.onTint,
      fontSize: 16,
      fontWeight: 'bold',
    },
    noPlansContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      padding: 40,
    },
    noPlansText: {
      color: colors.text,
      fontSize: 18,
      fontWeight: 'bold',
      textAlign: 'center',
      marginTop: 16,
    },
    noPlansSubtext: {
      color: colors.muted,
      fontSize: 14,
      textAlign: 'center',
      marginTop: 8,
    },
    paymentStatusBanner: {
      backgroundColor: colors.cardBg,
      borderColor: colors.tint,
      borderWidth: 1,
      padding: 12,
      borderRadius: 8,
      marginBottom: 16,
    },
    paymentStatusText: {
      color: colors.tint,
      fontSize: 14,
      textAlign: 'center',
    },
    paymentConfig: {
      backgroundColor: isDark ? '#111111' : '#FFFFFF',
      borderColor: colors.border,
      borderWidth: 1,
      borderRadius: 8,
      padding: 12,
      marginBottom: 16,
    },
    configTitle: {
      color: colors.text,
      fontSize: 16,
      fontWeight: '600',
      marginBottom: 8,
    },
    methodRow: { flexDirection: 'row', gap: 8 },
    methodPill: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingVertical: 8,
      paddingHorizontal: 12,
      borderRadius: 18,
      borderWidth: 1,
      borderColor: isDark ? '#555' : '#AAA',
      marginRight: 8,
    },
    methodPillActive: {
      backgroundColor: colors.tint,
      borderColor: colors.tint,
    },
    methodPillText: { color: colors.text, fontSize: 14 },
    methodPillTextActive: { color: colors.onTint, fontWeight: '700' },
    configLabel: { color: colors.muted, fontSize: 12, marginBottom: 6 },
    emailInput: {
      backgroundColor: colors.cardBg,
      color: colors.text,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 8,
      paddingHorizontal: 12,
      height: 40,
    },
  });

  return { ...styles, colors };
};
