name: Copilot Audit Frontend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repo
        uses: actions/checkout@v3

      - name: Instalar Copilot CLI
        run: |
          npm install -g @githubnext/copilot-cli

      - name: Ejecutar auditoría con Copilot
        run: |
          copilot \
            --agent .github/copilot-agents/audit-frontend.yml \
            --instructions .github/copilot-agents/copilot-audit-frontend.md
